In [1]:
import numpy as np
import pandas as pd

In [42]:
data=pd.read_csv(r'C:\Users\SAURABH\Desktop\Iris.csv')
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [5]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam


In [7]:
data1=data.drop('Id',axis=1)
data1.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
X=data1.drop('Species',axis=1)
y=data1['Species']

In [10]:
from sklearn.preprocessing import LabelEncoder
en=LabelEncoder()
y1=en.fit_transform(y)
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
Y=pd.get_dummies(y1).values
Y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=51)

In [39]:
X_train

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
50             7.0           3.2            4.7           1.4
64             5.6           2.9            3.6           1.3
42             4.4           3.2            1.3           0.2
59             5.2           2.7            3.9           1.4
93             5.0           2.3            3.3           1.0
..             ...           ...            ...           ...
110            6.5           3.2            5.1           2.0
122            7.7           2.8            6.7           2.0
105            7.6           3.0            6.6           2.1
16             5.4           3.9            1.3           0.4
57             4.9           2.4            3.3           1.0

[120 rows x 4 columns]

In [38]:
X_test

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
78             6.0           2.9            4.5           1.5
121            5.6           2.8            4.9           2.0
99             5.7           2.8            4.1           1.3
36             5.5           3.5            1.3           0.2
92             5.8           2.6            4.0           1.2
107            7.3           2.9            6.3           1.8
131            7.9           3.8            6.4           2.0
144            6.7           3.3            5.7           2.5
10             5.4           3.7            1.5           0.2
126            6.2           2.8            4.8           1.8
127            6.1           3.0            4.9           1.8
4              5.0           3.6            1.4           0.2
73             6.1           2.8            4.7           1.2
123            6.3           2.7            4.9           1.8
136            6.3           3.4            5.6           2.4
70             5.9           3.2            4.8           1.8
119            6.0           2.2            5.0           1.5
100            6.3           3.3            6.0           2.5
117            7.7           3.8            6.7           2.2
43             5.0           3.5            1.6           0.6
145            6.7           3.0            5.2           2.3
111            6.4           2.7            5.3           1.9
31             5.4           3.4            1.5           0.4
45             4.8           3.0            1.4           0.3
58             6.6           2.9            4.6           1.3
135            7.7           3.0            6.1           2.3
21             5.1           3.7            1.5           0.4
14             5.8           4.0            1.2           0.2
15             5.7           4.4            1.5           0.4
101            5.8           2.7            5.1           1.9

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [17]:
X_test

array([[ 0.26596461, -0.29631376,  0.47596309,  0.4699413 ],
       [-0.21944608, -0.53820255,  0.70743451,  1.13969136],
       [-0.09809341, -0.53820255,  0.24449168,  0.20204127],
       [-0.34079876,  1.15501895, -1.37580822, -1.27140888],
       [ 0.02325926, -1.02198012,  0.18662383,  0.06809126],
       [ 1.84354935, -0.29631376,  1.51758446,  0.87179134],
       [ 2.57166539,  1.88068531,  1.57545231,  1.13969136],
       [ 1.11543332,  0.67124138,  1.17037734,  1.80944143],
       [-0.46215143,  1.63879652, -1.26007251, -1.27140888],
       [ 0.50866995, -0.53820255,  0.64956666,  0.87179134],
       [ 0.38731728, -0.05442498,  0.70743451,  0.87179134],
       [-0.94756212,  1.39690773, -1.31794036, -1.27140888],
       [ 0.38731728, -0.53820255,  0.5916988 ,  0.06809126],
       [ 0.63002263, -0.78009133,  0.70743451,  0.87179134],
       [ 0.63002263,  0.91313016,  1.11250948,  1.67549142],
       [ 0.14461193,  0.42935259,  0.64956666,  0.87179134],
       [ 0.26596461, -1.

In [18]:
X_train

array([[ 1.47949133,  0.42935259,  0.5916988 ,  0.33599128],
       [-0.21944608, -0.29631376, -0.04484759,  0.20204127],
       [-1.67567815,  0.42935259, -1.37580822, -1.27140888],
       [-0.70485677, -0.78009133,  0.12875597,  0.33599128],
       [-0.94756212, -1.74764647, -0.21845115, -0.19980877],
       [ 0.63002263, -1.2638689 ,  0.70743451,  0.4699413 ],
       [-0.34079876, -1.02198012,  0.41809524,  0.06809126],
       [-0.09809341, -0.05442498,  0.30235953,  0.06809126],
       [ 0.38731728, -0.53820255,  0.18662383,  0.20204127],
       [-0.34079876, -1.50575769,  0.01302027, -0.19980877],
       [-0.21944608, -0.05442498,  0.24449168,  0.20204127],
       [ 2.32896004, -1.02198012,  1.86479158,  1.5415414 ],
       [-0.34079876, -1.50575769,  0.07088812, -0.06585876],
       [-0.34079876,  2.84824045, -1.31794036, -1.27140888],
       [ 0.7513753 ,  0.18746381,  1.05464163,  0.87179134],
       [-0.70485677,  2.60635166, -1.26007251, -1.40535889],
       [ 0.38731728, -1.

In [19]:
model=Sequential()
model.add(Dense(4,input_shape=(4,),activation='relu'))
model.add(Dense(3,activation='softmax'))

In [20]:
model.compile(optimizer='Adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [32]:
model.fit(X_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
12/12 [==============================] - 0s 3ms/step - loss: 0.4850 - accuracy: 0.8417
Epoch 2/100
12/12 [==============================] - 0s 2ms/step - loss: 0.4754 - accuracy: 0.8417
Epoch 3/100
12/12 [==============================] - 0s 2ms/step - loss: 0.4665 - accuracy: 0.8333
Epoch 4/100
12/12 [==============================] - 0s 3ms/step - loss: 0.4573 - accuracy: 0.8333
Epoch 5/100
12/12 [==============================] - 0s 2ms/step - loss: 0.4485 - accuracy: 0.8500
Epoch 6/100
12/12 [==============================] - 0s 2ms/step - loss: 0.4410 - accuracy: 0.8500
Epoch 7/100
12/12 [==============================] - 0s 3ms/step - loss: 0.4330 - accuracy: 0.8500
Epoch 8/100
12/12 [==============================] - 0s 2ms/step - loss: 0.4251 - accuracy: 0.8500
Epoch 9/100
12/12 [==============================] - 0s 3ms/step - loss: 0.4176 - accuracy: 0.8583
Epoch 10/100
12/12 [==============================] - 0s 3ms/step - loss: 0.4104 - accuracy: 0.8583
Epoch 11/

12/12 [==============================] - 0s 3ms/step - loss: 0.1557 - accuracy: 0.9667
Epoch 84/100
12/12 [==============================] - 0s 4ms/step - loss: 0.1542 - accuracy: 0.9667
Epoch 85/100
12/12 [==============================] - 0s 3ms/step - loss: 0.1523 - accuracy: 0.9583
Epoch 86/100
12/12 [==============================] - 0s 4ms/step - loss: 0.1508 - accuracy: 0.9583
Epoch 87/100
12/12 [==============================] - 0s 3ms/step - loss: 0.1493 - accuracy: 0.9667
Epoch 88/100
12/12 [==============================] - 0s 3ms/step - loss: 0.1478 - accuracy: 0.9667
Epoch 89/100
12/12 [==============================] - 0s 3ms/step - loss: 0.1462 - accuracy: 0.9667
Epoch 90/100
12/12 [==============================] - 0s 3ms/step - loss: 0.1448 - accuracy: 0.9583
Epoch 91/100
12/12 [==============================] - 0s 4ms/step - loss: 0.1434 - accuracy: 0.9583
Epoch 92/100
12/12 [==============================] - 0s 4ms/step - loss: 0.1420 - accuracy: 0.9583
Epoch 93/100


In [33]:
model.evaluate(X_test,y_test)

1/1 [==============================] - 0s 0s/step - loss: 0.1533 - accuracy: 0.9333


[0.1532522588968277, 0.9333333373069763]

# Here the accuracy is 93.33%

In [34]:
y_pred=model.predict(X_test)

In [40]:
y_pred[10].round(2)

array([0.  , 0.24, 0.76], dtype=float32)

In [43]:
np.argmax(y_pred[10].round(2))

2

Here the number 2 shows that if we give index 10th information of our X_test dataset to our model then it predict that the
species from class 2 which means the species is iris-virginica

In [44]:
model.save('iris_dataset.h5')

In [45]:
model_deploy=keras.models.load_model('iris_dataset.h5')